<?php

module_load_include('inc', 'marathons', 'includes/marathons.helpers');
include_once 'features/marathons.features.inc';

/*
 * Implements hook_permission
 */
function marathons_permission(){
  return array(
    'administer marathons' => array(
      'title' => t('Manage marathons')
    ),
    'import events' => array(
      'title' => t('Import new events'),
    ),
    'export events' => array(
      'title' => t('Export events list'),
    ),
  );
}

/*
 * Implements hook_menu
 */
function marathons_menu() {
  $items['admin/content/marathons'] = array(
    'title' => 'Marathons',
    'page callback' => 'marathon_overview',
    'file' => 'includes/marathons.admin.inc',
    'access arguments' => array('administer marathons'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/marathons/overview'] = array(
    'title' => 'Overview',
    'page callback' => 'marathon_overview',
    'access arguments' => array('administer marathons'),
    'file' => 'includes/marathons.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
//  $items['admin/content/marathons/export'] = array(
//    'title' => 'Export list',
//    'page callback' => 'marathon_output_csv',
//    'access arguments' => array('export events'),
//    'file' => 'includes/marathons.admin.inc',
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 1,
//  );
  $items['admin/content/marathons/import'] = array(
    'title' => 'Import file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('marathon_import_csv_form'),
    'file' => 'includes/marathons.admin.inc',
    'access arguments' => array('import events'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  return $items;
}

/*
 * Impmentation of hook_migrate_api()
 */
function marathons_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'marathons' => array('class_name' => 'MarathonsMigration'),
    )
  );
  return $api;
}


/*
 * Implements hook_markers_alter
 */

function marathons_markers_alter($markers) {
  foreach($markers as $key => $marker){
    if (isset($marker['field_event_date'])) {
      $markers[$key]['month'] =  format_date($marker['field_event_date'], 'custom', 'n');
    }
  }
  return $markers;
}

/**
 * Implements hook_ds_fields_info().
 */
function marathons_ds_fields_info($entity_type) {
  $fields = array();

  $defaults = array(
    'file' => drupal_get_path('module', 'marathons') . '/includes/marathons.ds.inc',
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('marathon|*'),
  );

  $fields['infowindow_show_details'] = array(
    'title' => t('Show Marathon Details'),
    'function' => 'infowindow_show_details_content',
  ) + $defaults;

  return array('node' => $fields);
}